---
#
# Media center
# Tested on: Debian 8.6 Jessie
# Updated & tested: 12/10/2016
#
# This builds a media center using Kodi, tvheadend & LTSP. At the end you should have the following
# - Main server with Kodi and lots of software for work, rest and play
# - Fat clients booting from the main server with Kodi & some software for basic browsing/email.
#
# Run
# ansible-playbook media_center.yml -b -v
# -b become sudo
# -v verbose
#
- hosts: media-servers
  user: kodi
  sudo: yes
  vars_files:
    - "vars/defaults.yml"
    - "vars/$ansible_distribution-$ansible_architecture.yml"
    - "vars/$ansible_distribution.yml"
    - "vars/custom.yml"

  # Tasks for XBMC are put in a specific order
  tasks:
    # Install system tools
    - include: common/tasks/add_testing_repo.yml
    - include: common/tasks/system.yml
    - include: common/tasks/email.yml
    - include: common/tasks/ruby.yml
    - include: common/tasks/backup.yml

    # Install multimedia and thin clients
    - include: common/tasks/kodi.yml
    - include: common/tasks/ltsp.yml
    - include: common/tasks/ltsp-fat-client.yml
    - include: common/tasks/ltsp-build.yml
    - include: common/tasks/tvheadend.yml

    # Install office and admin related software
    - include: common/tasks/office.yml 
    - include: common/tasks/x2go.yml

    # Copy sources.list from server to LTSP
    # This is not always required, but in the multimedia servers I like to do it.
    - name: Copy sources.list
      copy: src=/etc/apt/sources.list dest=/opt/ltsp/amd64/etc/apt/sources.list backup=yes
      
  handlers:
    - include: common/handlers/handlers.yml
