---
#
# Webserver for running Ruby on Rails with postgresql & node.
#
# Run
# ansible-playbook webserver.yml -b -v
# -b become sudo
# -v verbose

- hosts: webservers
  user: deploy
  vars:
    locale: 
      locale: "en_AU.UTF-8"
      language: "en_AU:en"
      numeric: "en_AU.UTF-8"
      time: "en_AU.UTF-8"
      monetary: "en_AU.UTF-8"
      paper: "en_AU.UTF-8"
      identification: "en_AU.UTF-8"
      name: "en_AU.UTF-8"
      address: "en_AU.UTF-8"
      telephone: "en_AU.UTF-8"
      measurement: "en_AU.UTF-8"
    rbenv:
      env: system
      version: v1.1.0
      default_ruby: 2.5.1
      rubies:
        - version: 2.5.1
          env:
            RUBY_CONFIGURE_OPTS: "--enable-shared"
      default_gems_file: common/files/default-gems

  roles:
    - role: zzet.rbenv
      rbenv_users:
        - "{{ ansible_user }}"
    # Install passenger & apache
    - role: mtpereira.passenger
      passenger_webserver: apache
      become: yes
      
  vars_files:
    - "vars/defaults.yml"
    - "vars/{{ ansible_distribution }}-{{ ansible_architecture }}.yml"
    - "vars/{{ ansible_distribution }}.yml"

  pre_tasks:
    - name: Ensure a locale exists
      locale_gen:
        name: en_AU.UTF-8
        state: present
    - include: common/tasks/add_repositories.yml
      become: yes
    - include: common/tasks/compression-tools.yml
          
  tasks:
    - include: common/tasks/system-webserver.yml
      become: yes
    - include: common/tasks/node.yml
    - include: common/tasks/email-server.yml
      become: yes
    - include: common/tasks/ruby.yml
    - include: common/tasks/rails-dependencies.yml
    - include: common/tasks/postgresql.yml
      become: yes
    - include: common/tasks/monit.yml
      become: yes
    - include: common/tasks/yarn.yml
      become: yes
    - include: common/tasks/redis.yml
    - include: common/tasks/backup.yml
    - include: common/tasks/letsencrypt.yml
      become: yes
    - include: common/tasks/fonts.yml
      become: yes
    - include: common/tasks/wkhtmltopdf.yml
      become: yes
      tags: focus

    # Fixes
    - include: common/tasks/mtpereira.passenger_fix.yml
      become: yes

  handlers:
    - include: common/handlers/handlers.yml
