---
#
# Apache 2 installation
#
# Requires: rbenv.yml
#

- name: Install Apache2
  apt: pkg=apache2 state=latest

- name: Install required packages
  action: apt pkg={{ item }}
  with_items:
    - apache2-dev
    - libcurl4-openssl-dev
    - libapr1-dev
    - libaprutil1-dev

