---
#
# Email installation under Debian
#

- name: Install exim4
  apt: pkg=exim4 state=installed

# Setup exim4
- name: Configure exim4
  copy:
    src: common/files/update-exim4.conf.conf
    dest: /etc/exim4/update-exim4.conf.conf
  notify:
    - restart exim4
