---
#
# LTSP fat clients, 
#
# Mostly used in multimedia streaming devices as they demand a lot from the server so
# we like to put this media processing onto the clients.
#

# Add items to the chroot section

# Add desktop (must use aptitude so it sets the configuration correctly)
- name: LTSP CHROOT - Convert thin-client to fat-client by installing a desktop environment
  command: ltsp-chroot -m apt-get install xfce4 -y

# Add kodi

# # BROKEN
# - name: Install add-apt-repository
#   command: ltsp-chroot -m 'aptitude install python-software-properties -y'

- name: LTSP CHROOT - Add multimedia testing repository
  command: cp /etc/apt/sources.list.d/www_deb_multimedia_org.list /opt/ltsp/amd64/etc/apt/sources.list.d
  when: ansible_os_family == "Debian"

- name: LTSP CHROOT - Update repo for chroot
  command: ltsp-chroot -m apt-get update

# --------------------------------------------------------------------------------
# Install applications in chroot section
# --------------------------------------------------------------------------------

# Had to use apt-get as I couldn't get aptitude to install without questions
- name: LTSP CHROOT - Install latest kodi
  command: ltsp-chroot -m apt-get install --force-yes -y {{ item }} 
  with_items:
    - kodi
    - mysql-client              # Required for testing only.
    - kodi-pvr-hts

- name: LTSP CHROOT - Install office and admin tools
  command: ltsp-chroot -m apt-get install --force-yes -y {{ item }} 
  with_items:
    - firefox-esr
    - icedove
    - firmware-linux-nonfree


# --------------------------------------------------------------------------------
# LTS.CONF
# --------------------------------------------------------------------------------
- name: LTSP CHROOT - Copy over standard lts.conf config file
  copy: src=common/files/lts.conf dest=/opt/ltsp/amd64/etc/lts.conf.example
