---
#
# LTSP - setup a Linux Terminal Server for PXE boot
#
# Only works in NFS mode.
#

- name: Install LTSP & related tools
  apt: pkg={{ item }} force=yes
  with_items:
    - ltsp-server
    - ltspfs
  notify: reload nfs

- name: Install epoptes
  apt: pkg=epoptes

- name: Add {{ ansible_ssh_user }} to epoptes
  action: command bash -c "for user in `ls /home`; do usermod -a -G epoptes {{ ansible_ssh_user }}; done"
  become: yes
  ignore_errors: yes

- name: Add fuse group
  group: name=fuse state=present

- name: Add all users to fuse group for local mounting
  action: command bash -c "for user in `ls /home`; do usermod -a -G fuse {{ ansible_ssh_user }}; done"
  become: yes
  ignore_errors: yes
  
- name: Copy LTSP configuration accross
  copy: src=common/files/ltsp-build-client.conf dest=/etc/ltsp/ltsp-build-client.conf

# --------------------------------------------------------------------------------
# Build thin client
#
# NOTE: Sometimes there are some errors, but these can be safely ignored
# --------------------------------------------------------------------------------
- name: Build thin client
  action: command ltsp-build-client creates=/opt/ltsp/amd64
  ignore_errors: yes

# ## Debian recommends we run LTSP in NFS mode, not NBD mode
# - name: Add LTSP to exports
#   lineinfile:
#     dest=/etc/exports
#     regexp="^/opt/ltsp"
#     line="/opt/ltsp *(ro,no_root_squash,async,no_subtree_check)"
#     backup=yes
#     state=present
#   notify: reload nfs

## Debian recommends we run LTSP in NFS mode, not NBD mode
## I have noticed on some systems /etc/exportsfs is missing completely after installation
## of LTSP, so let's copy our file.
- name: Copy exports
  copy: src=common/files/exports dest=/etc
  notify: reload nfs

# --------------------------------------------------------------------------------
# WORKAROUNDS
# --------------------------------------------------------------------------------
  
# #
# # Pulseaudio fixes
# #
# - name: Copy asound.conf
#   copy: src=common/files/asound.conf dest=/etc/asound.conf backup=yes

# - name: WORKAROUND - Copy Pulseaudio startup file
#   copy: src="common/files/PulseAudio load module.desktop" dest="/tmp/PulseAudio load module.desktop"
  
# - name: WORKAROUND - Load module-suspend-on-idle in users startup
#   action: command bash -c "for user in `ls /home`; do cp '/tmp/PulseAudio load module.desktop' /home/{{ ansible_ssh_user }}/.config/autostart; done"
#   ignore_errors: yes
  

# #
# # Copy over intel xorg settings to force HD resolution
# #
# - name: Copy intel_xorg.conf
#   copy: src=common/files/intel_xorg.conf dest=/opt/ltsp/i386/etc/X11

#
# Work around for network manager to work with tftpd
#
# Refer Debian bug 771441: http://tinyurl.com/owebjgz 
#
- name: Fix tftpd-hpa to start properly
  lineinfile:
    dest=/etc/default/tftpd-hpa
    regexp="^TFTP_ADDRESS"
    line='TFTP_ADDRESS=":69"'
    backup=yes
    state=present
  
