---

# - name: Install nvidia
#   apt: pkg=libvdpau1 state=latest
#   apt: pkg=nvidia-vdpau-driver state=latest


# installed nvidia-xconfig nvidia-glx
- name: Install nvidia
  apt: pkg={{ item }} state=latest
  with_items:
    - nvidia-xconfig
    - nvidia-glx
  
# ran 'sudo nvidia-xconfig' to create a xorg file & it loads
# - name: Setup nvidia
#   command: nvidia-xconfig
