---
#
# Install Passenger to allow Rails applications to work through the Apache HTTP server.
#

- name: Install Passenger
  apt: pkg=libapache2-mod-passenger state=latest

- name: Enable passenger apache module
  action: command a2enmod passenger
  notify: restart apache
  
# - name: Install Passenger apache2 module
#   action: command passenger-install-apache2-module -a
  
# - name: Add the passenger module to the apache2 config
#   template: src=common/templates/passenger.load.j2 dest=/etc/apache2/mods-enabled/passenger.load mode=0644
#   notify: restart apache

- name: Copy over example file for rails project config
  copy: src=common/files/rails_project dest=/etc/apache2/sites-enabled/rails_project mode=0644 force=no
