---
#
# Install PostgreSQL
#
- name: Install postgresql requirements
  action: apt pkg={{ item }} force=yes state=latest
  with_items:
    - python-psycopg2
    - libpq-dev

# https://coderwall.com/p/hdul2g - Update locale & timezone
# This is required so that PostgreSQL installs with UTF-8 support.
# - name: set locale to $locale
#   command: /usr/sbin/update-locale LANG=$locale LC_ALL=$locale

- name: Install postgresql
  apt:
    name: postgresql
    state: latest

# Postgresql create user
# If problems here make sure you add the following to your /etc/sudoers
# %sudo   ALL= (postgres) NOPASSWD: ALL
#
# Issues;
# https://stackoverflow.com/questions/35619477/ansible-create-a-postgres-user
#
- name: Create postgresql user
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_user: user={{ansible_ssh_user}} password={{db_passwd}} role_attr_flags=CREATEDB,NOSUPERUSER

