---
#
# System GUI related tasks and tools
#

- name: Connectivity
  action: apt pkg={{ item }} state=latest force=yes
  with_items:
    - blueman                   # bluetooth control

- name: Remote support
  action: apt pkg={{ item }} state=latest force=yes
  with_items:
    - remmina
    - remmina-plugin-nx
    - remmina-plugin-vnc

- name: GUI tools
  action: apt pkg={{ item }} state=latest force=yes
  with_items:
    - font-manager
    - ttf-mscorefonts-installer
    - devilspie                 # Save window placement
    - terminator
