---
#
# X2Go allows remote access amoungst other things (PXE boot)
#
# I only use X2Go for remote access at the moment.
#

## Issue: Just hangs there, this is supposed to take 4 seconds. I had to do it manually on the server;
## sudo -s
## apt-key adv --recv-keys --keyserver keys.gnupg.net E1F958385BFE2B6E
##
# - name: Add X2Go key
#   command: apt-key adv --recv-keys --keyserver keys.gnupg.net E1F958385BFE2B6E
#   when: ansible_os_family == "Debian"

## Issue: unsupported parameter for module: keyserver
# - name: Add X2Go key
#   apt_key: keyserver=keys.gnupg.net id=E1F958385BFE2B6E state=present
#   when: ansible_os_family == "Debian"

- name: Add X2Go repository
  apt_repository: repo='deb http://packages.x2go.org/debian {{ ansible_distribution_release }} main'
  when: ansible_os_family == "Debian" and ansible_distribution_release != "stretch/sid"

- name: Add X2Go repository
  apt_repository: repo='deb http://packages.x2go.org/debian testing main'
  when: ansible_os_family == "Debian" and ansible_distribution_release == "stretch/sid"

- name: Install x2go-keyring
  apt: pkg=x2go-keyring update_cache=yes state=present
  when: ansible_os_family == "Debian" and ansible_distribution_release != "stretch/sid"

- name: Add X2Go repository for Ubuntu based distros
  apt_repository: repo='ppa:x2go/stable' update_cache=yes
  when: ansible_os_family == "Ubuntu" or ansible_os_family == "Linuxmint"

- name: Install x2goserver
  apt: pkg={{ item }} state=present
  with_items:
    - x2goclient
    - x2goserver
    - x2goserver-xsession
    - x2goserver-fmbindings
    - cups-x2go
    - x2godesktopsharing

- name: Setup SSH to be compatible with x2go
  lineinfile:
    dest=/etc/ssh/sshd_config
    backrefs=yes
    regexp="^HostKey /etc/ssh/ssh_host_ecdsa_key"
    line="#HostKey /etc/ssh/ssh_host_ecdsa_key"
    backup=yes
    state=present
  notify: restart ssh
  when: ansible_os_family == "Debian"

  
